import { useEffect } from 'react'
import styles from './styles/App.module.css'

export default function App() {
  useEffect(() => {
    // Register PWA service worker
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('/sw.js', { scope: '/' }).catch(() => {
        // PWA service worker will be generated by vite-plugin-pwa
      })
    }
  }, [])

  return (
    <div className={styles.root}>
      <header className={styles.header}>
        <div className={styles.headerIn}>
          <div className={styles.brand}>Ledger</div>
          <div className={styles.topMeta}>
            <b>Today</b>
            <span>Ready to lift</span>
          </div>
        </div>
      </header>

      <main className={styles.wrap}>
        <div style={{ padding: '40px 20px', textAlign: 'center' }}>
          <h1>Scaffolding React App...</h1>
          <p>Phase 1 setup in progress. Stores and components coming next.</p>
        </div>
      </main>

      <nav className={styles.tabs}>
        <div className={styles.tabsIn}>
          <button className={`${styles.tab} ${styles.on}`}>
            <svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="2"/></svg>
            Today
          </button>
          <button className={styles.tab}>
            <svg viewBox="0 0 24 24"><path d="M3 9h18M9 3v18"/></svg>
            History
          </button>
          <button className={styles.tab}>
            <svg viewBox="0 0 24 24"><path d="M3 3v18h18V3"/></svg>
            Trends
          </button>
          <button className={styles.tab}>
            <svg viewBox="0 0 24 24"><path d="M3 12h18M3 6h18M3 18h18"/></svg>
            Sync
          </button>
        </div>
      </nav>
    </div>
  )
}
