import { useEffect } from 'react'
import { useConfigStore, useUIStore, useSessionStore } from '@/store'
import { Header, BottomNav, Toast } from '@/components/layout'
import { TodayTab, HistoryTab, TrendsTab, SyncTab } from '@/components/tabs'
import { RestTimer } from '@/components/session'
import { streak } from '@/services/trendCalculations'
import styles from '@/styles/App.module.css'

export default function App() {
  const activeTab = useUIStore((s) => s.activeTab)
  const setTab = useUIStore((s) => s.setTab)
  const loadConfig = useConfigStore((s) => s.loadConfig)
  const loadWeights = useConfigStore((s) => s.loadWeights)
  const clearDraft = useSessionStore((s) => s.clearDraft)
  const sessions = useSessionStore((s) => s.sessions)

  useEffect(() => {
    // Initialize config and weights
    loadConfig()
    loadWeights()

    // Register PWA service worker
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('/sw.js', { scope: '/' }).catch(() => {
        // PWA service worker will be generated by vite-plugin-pwa
      })
    }
  }, [loadConfig, loadWeights])

  const today = new Date()
  const todayStr = today.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })

  return (
    <div className={styles.root}>
      <Header date={todayStr} streak={streak(sessions)} onLogoClick={() => { clearDraft(); setTab('today') }} />

      <main className={styles.wrap}>
        {activeTab === 'today' && <TodayTab />}
        {activeTab === 'history' && <HistoryTab />}
        {activeTab === 'trends' && <TrendsTab />}
        {activeTab === 'sync' && <SyncTab />}
      </main>

      <RestTimer />
      <BottomNav activeTab={activeTab} onTabChange={setTab} />
      <Toast />
    </div>
  )
}
